#!/usr/bin/env bash
# Nginx must be running, and listening on port 80 of all the server’s active IPv4 IPs
# Configures a server to the above requirements
rm /etc/nginx/sites-enabled/default 
# Create a symbolic link to enable the default site
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# Restart Nginx
service nginx restart
