#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd.
# script should only display:
# > username
# > user id
# > Home directory path for the user

file="/etc/passwd"
while IFS=: read -r username _ uid _ _ home _; do
    echo "Username: $username"
    echo "User ID: $uid"
    echo "Home Directory: $home"
done < "$file"
