#!/usr/bin/env bash
# This script displays "Time <hours : minutes>"
hour=1
while [ $hour -le 12 ]
do
    echo "Hour: $hour"
    minute=1
    while [ $minute -le 59 ]
    do
        echo "$minute"
        ((minute++))
    done
    ((hour++))
done
